export type ListingKind = "STAY" | "ATTRACTION" | "TAXI" | "RESTAURANT";

export type MarketItem = {
  slug: string;
  kind: ListingKind;
  name: string;
  nastaliq: string;
  city: string;
  region: string;
  cover: string;
  description: string;
  price: number;
  priceUnit: "night" | "day" | "person" | "table";
  ownerEmail: string;
  lat?: number;
  lng?: number;
  address?: string;
};

export const attractions: MarketItem[] = [
  {
    slug: "imam-ali",
    kind: "ATTRACTION",
    name: "Imam Ali shrine",
    nastaliq: "حرم امام علی",
    city: "Najaf",
    region: "Iraq",
    cover: "/images/stay-walled-city.png",
    description: "The heart of Najaf. Walking plan with a local companion.",
    price: 0,
    priceUnit: "person",
    ownerEmail: "attraction.owner@serai.pk",
  },
  {
    slug: "imam-hussain",
    kind: "ATTRACTION",
    name: "Imam Hussain & Abbas",
    nastaliq: "کربلا",
    city: "Karbala",
    region: "Iraq",
    cover: "/images/dest-lahore.png",
    description: "Between the two harams. Timed around prayer.",
    price: 0,
    priceUnit: "person",
    ownerEmail: "attraction.owner@serai.pk",
  },
  {
    slug: "kadhimiya",
    kind: "ATTRACTION",
    name: "Kadhimiya",
    nastaliq: "کاظمین",
    city: "Baghdad",
    region: "Iraq",
    cover: "/images/stay-canal-breeze.png",
    description: "Kazimayn, then return to your hotel.",
    price: 4500,
    priceUnit: "person",
    ownerEmail: "attraction.owner@serai.pk",
  },
  {
    slug: "imam-reza",
    kind: "ATTRACTION",
    name: "Imam Reza shrine",
    nastaliq: "حرم امام رضا",
    city: "Mashhad",
    region: "Iran",
    cover: "/images/stay-apricot-court.png",
    description: "Stay near the haram. Walking, not a checklist.",
    price: 0,
    priceUnit: "person",
    ownerEmail: "attraction.owner@serai.pk",
  },
  {
    slug: "fatima-masumeh",
    kind: "ATTRACTION",
    name: "Hazrat Masumeh",
    nastaliq: "قم",
    city: "Qom",
    region: "Iran",
    cover: "/images/stay-orchard.png",
    description: "Qom haram and the lanes around it.",
    price: 0,
    priceUnit: "person",
    ownerEmail: "attraction.owner@serai.pk",
  },
  {
    slug: "haram-makkah",
    kind: "ATTRACTION",
    name: "Masjid al-Haram",
    nastaliq: "الحرم المكي",
    city: "Makkah",
    region: "Saudi Arabia",
    cover: "/images/dest-hunza.png",
    description: "Hotel-to-haram walking times and prayer windows.",
    price: 0,
    priceUnit: "person",
    ownerEmail: "attraction.owner@serai.pk",
  },
  {
    slug: "rawdah",
    kind: "ATTRACTION",
    name: "Masjid an-Nabawi",
    nastaliq: "المسجد النبوي",
    city: "Madinah",
    region: "Saudi Arabia",
    cover: "/images/dest-skardu.png",
    description: "Rawdah slot guidance with your dates.",
    price: 0,
    priceUnit: "person",
    ownerEmail: "attraction.owner@serai.pk",
  },
];

export const taxis: MarketItem[] = [
  {
    slug: "najaf-hiace",
    kind: "TAXI",
    name: "Najaf → Kufa",
    nastaliq: "نجف → کوفہ",
    city: "Najaf",
    region: "Iraq",
    cover: "/images/stay-truck-art.png",
    description: "Shared HiAce from Najaf hotels to Kufa. Per person or private van.",
    price: 3500,
    priceUnit: "person",
    ownerEmail: "taxi.owner@serai.pk",
  },
  {
    slug: "karbala-coaster",
    kind: "TAXI",
    name: "Karbala → Kufa",
    nastaliq: "کربلا → کوفہ",
    city: "Karbala",
    region: "Iraq",
    cover: "/images/exp-passu.png",
    description: "Coaster from Karbala to Kufa. Shared per person or the whole coach.",
    price: 4500,
    priceUnit: "person",
    ownerEmail: "taxi.owner@serai.pk",
  },
  {
    slug: "baghdad-innova",
    kind: "TAXI",
    name: "Baghdad → Kadhimiya & Samarra",
    nastaliq: "بغداد → کاظمین",
    city: "Baghdad",
    region: "Iraq",
    cover: "/images/dest-lahore.png",
    description: "Kazimayn then Samarra. Per person or private Innova.",
    price: 6000,
    priceUnit: "person",
    ownerEmail: "taxi.owner@serai.pk",
  },
  {
    slug: "mashhad-van",
    kind: "TAXI",
    name: "Mashhad → Qom",
    nastaliq: "مشهد → قم",
    city: "Mashhad",
    region: "Iran",
    cover: "/images/stay-apricot-court.png",
    description: "H1 between Mashhad and Qom. Per person or private van.",
    price: 8000,
    priceUnit: "person",
    ownerEmail: "taxi.owner@serai.pk",
  },
  {
    slug: "makkah-gmc",
    kind: "TAXI",
    name: "Makkah → Madinah",
    nastaliq: "مكة → المدينة",
    city: "Makkah",
    region: "Saudi Arabia",
    cover: "/images/dest-hunza.png",
    description: "Haramain road. Per person or the whole Yukon.",
    price: 12000,
    priceUnit: "person",
    ownerEmail: "taxi.owner@serai.pk",
  },
];

export const pilgrimStays: MarketItem[] = [
  {
    slug: "qasr-al-dur-najaf",
    kind: "STAY",
    name: "Qasr Al-Dur Hotel",
    nastaliq: "قصر الدر",
    city: "Najaf",
    region: "Iraq",
    cover: "/images/stay-walled-city.png",
    description: "A known hotel near the Imam Ali shrine. Walking distance to the holy courtyard.",
    price: 18500,
    priceUnit: "night",
    ownerEmail: "stay.owner@serai.pk",
    lat: 32.0258,
    lng: 44.3341,
    address: "Al-Haidariya / Old City, Najaf, Iraq",
  },
  {
    slug: "al-kafeel-karbala",
    kind: "STAY",
    name: "Al Kafeel Hotel",
    nastaliq: "الكفيل",
    city: "Karbala",
    region: "Iraq",
    cover: "/images/dest-lahore.png",
    description: "Between the two harams. Direct access toward Imam Hussain and Al-Abbas.",
    price: 24000,
    priceUnit: "night",
    ownerEmail: "stay.owner@serai.pk",
    lat: 32.6169,
    lng: 44.0336,
    address: "Between the Two Holy Shrines, Karbala, Iraq",
  },
  {
    slug: "darvishi-mashhad",
    kind: "STAY",
    name: "Darvishi Hotel",
    nastaliq: "هتل درویشی",
    city: "Mashhad",
    region: "Iran",
    cover: "/images/stay-apricot-court.png",
    description: "Large hotel on Imam Reza Street, beside the holy shrine.",
    price: 28500,
    priceUnit: "night",
    ownerEmail: "stay.owner@serai.pk",
    lat: 36.28705,
    lng: 59.61555,
    address: "Imam Reza St, Mashhad, Razavi Khorasan, Iran",
  },
  {
    slug: "astan-qom",
    kind: "STAY",
    name: "Astan Hotel Qom",
    nastaliq: "هتل آستان قم",
    city: "Qom",
    region: "Iran",
    cover: "/images/stay-orchard.png",
    description: "Close to Hazrat Masumeh shrine. Quiet rooms for ziyarat nights.",
    price: 19800,
    priceUnit: "night",
    ownerEmail: "stay.owner@serai.pk",
    lat: 34.6419,
    lng: 50.8778,
    address: "Near Holy Shrine of Fatima Masumeh, Qom, Iran",
  },
  {
    slug: "swissotel-makkah",
    kind: "STAY",
    name: "Swissôtel Makkah",
    nastaliq: "سويسوتيل مكة",
    city: "Makkah",
    region: "Saudi Arabia",
    cover: "/images/dest-hunza.png",
    description: "Ajyad, connected toward the haram. Timed lifts and prayer windows.",
    price: 62000,
    priceUnit: "night",
    ownerEmail: "stay.owner@serai.pk",
    lat: 21.4187,
    lng: 39.8256,
    address: "Ajyad St, Makkah 24231, Saudi Arabia",
  },
  {
    slug: "movenpick-madinah",
    kind: "STAY",
    name: "Anwar Al Madinah Mövenpick",
    nastaliq: "موفنبيك المدينة",
    city: "Madinah",
    region: "Saudi Arabia",
    cover: "/images/dest-skardu.png",
    description: "Facing the Prophet’s Mosque. Direct walking line to the haram.",
    price: 54000,
    priceUnit: "night",
    ownerEmail: "stay.owner@serai.pk",
    lat: 24.46735,
    lng: 39.61115,
    address: "King Fahd Rd, Al Haram, Madinah 42311, Saudi Arabia",
  },
];

export const restaurants: MarketItem[] = [];

export const ownerAccounts = [
  { email: "guest@serai.pk", name: "Ayesha Guest", role: "TRAVELER", ownerKind: null as string | null },
  { email: "stay.owner@serai.pk", name: "Saba Stay", role: "OWNER", ownerKind: "STAY" },
  { email: "attraction.owner@serai.pk", name: "Farid Sites", role: "OWNER", ownerKind: "ATTRACTION" },
  { email: "taxi.owner@serai.pk", name: "Omar Roads", role: "OWNER", ownerKind: "TAXI" },
  { email: "dine.owner@serai.pk", name: "Leila Table", role: "OWNER", ownerKind: "RESTAURANT" },
];

export const unitLabel: Record<string, string> = {
  night: "night",
  day: "day",
  person: "person",
  table: "meal",
};

export const kindLabel: Record<ListingKind, string> = {
  STAY: "Hotel",
  ATTRACTION: "Ziyarat",
  TAXI: "Taxi",
  RESTAURANT: "Food",
};

export const kindPath: Record<ListingKind, string> = {
  STAY: "stay",
  ATTRACTION: "attractions",
  TAXI: "taxis",
  RESTAURANT: "food",
};
