import type { Stay, Vibe } from "./types";

export const vibes: Vibe[] = [
  "Quiet courtyard",
  "Mountain mist",
  "Old-city rooftop",
  "Family haveli",
  "Desert silence",
  "Lakeside dawn",
  "Work-from-haveli",
  "Chef’s table",
];

const weather = [
  { d: "Thu", t: "18°" },
  { d: "Fri", t: "17°" },
  { d: "Sat", t: "16°" },
  { d: "Sun", t: "19°" },
  { d: "Mon", t: "21°" },
  { d: "Tue", t: "20°" },
  { d: "Wed", t: "18°" },
];

export const stays: Stay[] = [
  {
    id: "apricot-court",
    name: "The Apricot Court",
    nastaliq: "صحنِ زردآلو",
    city: "Karimabad",
    region: "Hunza",
    cover: "/images/stay-apricot-court.png",
    gallery: ["/images/stay-apricot-court.png", "/images/dest-hunza.png", "/images/stay-orchard.png", "/images/hero-hunza-dusk.png", "/images/exp-harvest.png"],
    vibes: ["Quiet courtyard", "Mountain mist", "Chef’s table"],
    type: "Court house",
    price: 42800,
    storyScore: 96,
    climate: "Best window: Oct–Apr",
    season: "good",
    weather,
    lat: 36.3167,
    lng: 74.665,
    pin: { x: 58, y: 9 },
    amenities: ["Wood-fired kitchen", "Courtyard hammock", "Hot water 6–10pm", "Stargazing roof"],
    rooms: [
      { id: "court", name: "Courtyard room", sleeps: 2, price: 42800, note: "Opens onto apricot trees" },
      { id: "peak", name: "Peak loft", sleeps: 3, price: 51200, note: "Rakaposhi at the foot of the bed" },
    ],
    stories: [
      { author: "Maya", from: "Karachi", body: "Breakfast arrived like a letter. The valley was still in shadow and the apricots were loud.", mood: "felt like a film still" },
      { author: "Tomas", from: "Lisbon", body: "No minibar. A brass key. A dog that knew the stairs better than I did.", mood: "quiet courtyard" },
      { author: "Ayesha", from: "Lahore", body: "Hum ne chai pi, phir chup. The silence had a temperature.", mood: "mountain mist" },
    ],
    experienceIds: ["passu", "harvest"],
    host: {
      name: "Saba",
      portrait: "/images/host-saba.png",
      years: 11,
      letter: "We keep this house the way my grandmother kept the orchard — a little stubborn, very clean, always a place for one more guest.",
    },
    description:
      "A stone court in Karimabad where apricot trees take the afternoon personally. Rooms are few, lamps are oil, and the mountains do not perform. You come for the hush between harvests and leave with dust on your shoes that smells faintly of woodsmoke.",
  },
  {
    id: "walled-roof",
    name: "Roof of the Walled City",
    nastaliq: "بامِ اندرون شہر",
    city: "Lahore",
    region: "Punjab",
    cover: "/images/stay-walled-city.png",
    gallery: ["/images/stay-walled-city.png", "/images/dest-lahore.png", "/images/stay-canal-breeze.png", "/images/stay-truck-art.png"],
    vibes: ["Old-city rooftop", "Family haveli", "Chef’s table"],
    type: "Haveli roof",
    price: 36500,
    storyScore: 94,
    climate: "Best window: Nov–Mar",
    season: "good",
    weather,
    lat: 31.588,
    lng: 74.31,
    pin: { x: 54, y: 44 },
    amenities: ["Rooftop supper", "Call to prayer at the window", "Library of Urdu first editions", "Driver on call"],
    rooms: [
      { id: "brick", name: "Brick suite", sleeps: 2, price: 36500, note: "Looks into the lane" },
      { id: "sky", name: "Sky room", sleeps: 2, price: 41900, note: "The city becomes a map" },
    ],
    stories: [
      { author: "Noura", from: "Amman", body: "The rooftop was a theatre. Kites, loudspeakers, a moon that belonged to someone else first.", mood: "old-city rooftop" },
      { author: "Bilal", from: "Islamabad", body: "Felt like a film still. The host left a couplet instead of a chocolate.", mood: "felt like a film still" },
    ],
    experienceIds: ["walled"],
    host: {
      name: "Farid",
      portrait: "/images/host-farid.png",
      years: 8,
      letter: "This roof has heard more arguments and more ghazals than I have. Stay long enough and it will add you to the ledger.",
    },
    description:
      "A restored brick haveli whose real room is the roof. At dusk the Walled City becomes a single instrument. You eat late, sleep later, and wake to a city that has already begun without you.",
  },
  {
    id: "indigo-well",
    name: "Indigo Well House",
    nastaliq: "نیل کنواں",
    city: "Multan",
    region: "Punjab",
    cover: "/images/stay-indigo-well.png",
    gallery: ["/images/stay-indigo-well.png", "/images/stay-desert-kiln.png", "/images/dest-lahore.png"],
    vibes: ["Quiet courtyard", "Family haveli", "Desert silence"],
    type: "Dye house",
    price: 27400,
    storyScore: 91,
    climate: "Best window: Nov–Feb",
    season: "shoulder",
    weather,
    lat: 30.157,
    lng: 71.525,
    pin: { x: 44, y: 54 },
    amenities: ["Dye courtyard", "Afternoon dark", "Blue-tiled well", "Slow breakfast"],
    rooms: [
      { id: "well", name: "Well chamber", sleeps: 2, price: 27400, note: "Cool even in May" },
      { id: "loom", name: "Loom room", sleeps: 3, price: 31800, note: "A working indigo shop below" },
    ],
    stories: [
      { author: "Elena", from: "Milan", body: "The well held the sky like a coin. I stayed an extra night without asking anyone.", mood: "quiet courtyard" },
    ],
    experienceIds: ["cholistan"],
    host: {
      name: "Leila",
      portrait: "/images/host-leila.png",
      years: 14,
      letter: "Indigo is a patient guest. So are we. Come dusty; leave a little bluer.",
    },
    description:
      "A dye-house turned inn around a deep well the colour of evening. Multan heat stops at the threshold. Inside: tiles, hush, and a family that still stains their hands for a living.",
  },
  {
    id: "black-granite",
    name: "Black Granite Camp",
    nastaliq: "کالا سنگ",
    city: "Skardu",
    region: "Baltistan",
    cover: "/images/stay-black-granite.png",
    gallery: ["/images/stay-black-granite.png", "/images/stay-granite-camp.png", "/images/dest-skardu.png", "/images/exp-passu.png"],
    vibes: ["Mountain mist", "Lakeside dawn", "Desert silence"],
    type: "Stone camp",
    price: 48900,
    storyScore: 97,
    climate: "Best window: May–Oct",
    season: "good",
    weather,
    lat: 35.297,
    lng: 75.633,
    pin: { x: 64, y: 14 },
    amenities: ["River terrace", "Down quilts", "Packed breakfast for passes", "Satellite quiet"],
    rooms: [
      { id: "cabin", name: "Granite cabin", sleeps: 2, price: 48900, note: "Stone that holds the cold" },
      { id: "river", name: "River tent-room", sleeps: 2, price: 44200, note: "Canvas, stove, glacier air" },
    ],
    stories: [
      { author: "Omar", from: "Dubai", body: "I woke because the river changed key. Then the light arrived like a verdict.", mood: "lakeside dawn" },
    ],
    experienceIds: ["skardu-lake"],
    host: {
      name: "Saba",
      portrait: "/images/host-saba.png",
      years: 6,
      letter: "We do not heat the whole valley. We heat the bed, the soup, and the hour you return.",
    },
    description:
      "A handful of black stone rooms above a glacial river. Skardu does not do soft. The camp does: quilts, broth, and a door that faces the right mountain.",
  },
  {
    id: "seawind",
    name: "Sea-wind Haveli",
    nastaliq: "ہوائے بحر",
    city: "Gwadar",
    region: "Balochistan",
    cover: "/images/stay-seawind.png",
    gallery: ["/images/stay-seawind.png", "/images/stay-seawind-haveli.png", "/images/dest-gwadar.png"],
    vibes: ["Desert silence", "Lakeside dawn", "Quiet courtyard"],
    type: "Coastal haveli",
    price: 33200,
    storyScore: 90,
    climate: "Best window: Nov–Mar",
    season: "good",
    weather,
    lat: 25.126,
    lng: 62.322,
    pin: { x: 12, y: 78 },
    amenities: ["Sea terrace", "Salt-air rooms", "Fish supper", "Night wind"],
    rooms: [
      { id: "cliff", name: "Cliff room", sleeps: 2, price: 33200, note: "The Arabian Sea as a neighbour" },
      { id: "court", name: "Court room", sleeps: 3, price: 29800, note: "Lime walls, less wind" },
    ],
    stories: [
      { author: "Hina", from: "Karachi", body: "The wind wrote on the shutters all night. I slept anyway.", mood: "desert silence" },
    ],
    experienceIds: ["gwadar-wind"],
    host: {
      name: "Farid",
      portrait: "/images/host-farid.png",
      years: 5,
      letter: "Gwadar is not a secret. It is simply far. We keep the lamps for people who come that far.",
    },
    description:
      "Limestone rooms that have learned the sea. Gwadar light is horizontal. You eat fish that was swimming at noon and watch the horizon refuse to finish.",
  },
  {
    id: "pine-key",
    name: "Pine Key Lodge",
    nastaliq: "چیڑ کی چابی",
    city: "Patriata",
    region: "Murree",
    cover: "/images/stay-pine-key.png",
    gallery: ["/images/stay-pine-key.png", "/images/stay-first-light.png", "/images/stay-river-lantern.png"],
    vibes: ["Mountain mist", "Family haveli", "Quiet courtyard"],
    type: "Hill lodge",
    price: 24600,
    storyScore: 88,
    climate: "Best window: Apr–Jun, Sep–Nov",
    season: "shoulder",
    weather,
    lat: 33.84,
    lng: 73.45,
    pin: { x: 42, y: 29 },
    amenities: ["Mist decks", "Fireplace", "Board games older than the lodge", "Rain capes"],
    rooms: [
      { id: "pine", name: "Pine room", sleeps: 2, price: 24600, note: "Needles against the glass" },
      { id: "family", name: "Family loft", sleeps: 5, price: 31200, note: "A table that seats arguments" },
    ],
    stories: [
      { author: "Sami", from: "Rawalpindi", body: "Clouds came indoors. The children thought the house was a ship.", mood: "mountain mist" },
    ],
    experienceIds: ["swat-river"],
    host: {
      name: "Leila",
      portrait: "/images/host-leila.png",
      years: 19,
      letter: "We have the key to a pine that is older than the road. The rest is soup and dry socks.",
    },
    description:
      "A timber lodge in Patriata mist, built for families who remember Murree before the traffic learned its name. Fires, wool, and a deck that disappears twice a day.",
  },
  {
    id: "canal-breeze",
    name: "Canal Breeze Studio",
    nastaliq: "نہر کی ہوا",
    city: "Lahore",
    region: "Punjab",
    cover: "/images/stay-canal-breeze.png",
    gallery: ["/images/stay-canal-breeze.png", "/images/stay-walled-city.png", "/images/dest-lahore.png"],
    vibes: ["Work-from-haveli", "Quiet courtyard", "Old-city rooftop"],
    type: "Canal studio",
    price: 19800,
    storyScore: 86,
    climate: "Best window: Oct–Mar",
    season: "good",
    weather,
    lat: 31.54,
    lng: 74.35,
    pin: { x: 56, y: 46 },
    amenities: ["Fibre that actually works", "Standing desk", "Canal light", "Noon hush"],
    rooms: [
      { id: "studio", name: "Canal studio", sleeps: 2, price: 19800, note: "A desk that faces water" },
    ],
    stories: [
      { author: "Rina", from: "Singapore", body: "I finished a chapter because the canal kept time better than I did.", mood: "work-from-haveli" },
    ],
    experienceIds: ["walled"],
    host: {
      name: "Saba",
      portrait: "/images/host-saba.png",
      years: 4,
      letter: "Bring your deadlines. Leave them by the plants. The canal does not care, which helps.",
    },
    description:
      "A single serious room on a Lahore canal: light, a desk, and the kind of quiet that is negotiated with the city rather than found.",
  },
  {
    id: "orchard-quiet",
    name: "Orchard Quiet",
    nastaliq: "باغ کی خاموشی",
    city: "Nagar",
    region: "Gilgit-Baltistan",
    cover: "/images/stay-orchard.png",
    gallery: ["/images/stay-orchard.png", "/images/stay-orchard-quiet.png", "/images/dest-hunza.png", "/images/stay-apricot-court.png"],
    vibes: ["Quiet courtyard", "Mountain mist", "Chef’s table"],
    type: "Orchard house",
    price: 35600,
    storyScore: 95,
    climate: "Best window: Sep–Nov, Apr–May",
    season: "good",
    weather,
    lat: 36.28,
    lng: 74.72,
    pin: { x: 60, y: 11 },
    amenities: ["Apple terrace", "No road noise", "Kitchen garden", "Dawn walks"],
    rooms: [
      { id: "orchard", name: "Orchard room", sleeps: 2, price: 35600, note: "Trees at the pillow" },
      { id: "terrace", name: "Terrace suite", sleeps: 3, price: 40100, note: "Breakfast outside even in frost" },
    ],
    stories: [
      { author: "Jules", from: "Lyon", body: "The orchard made its own weather. I stopped checking the phone for three days.", mood: "quiet courtyard" },
    ],
    experienceIds: ["harvest", "passu"],
    host: {
      name: "Leila",
      portrait: "/images/host-leila.png",
      years: 9,
      letter: "Nagar is Hunza’s quieter sibling. We prefer it that way, and so will you, after the second tea.",
    },
    description:
      "An orchard house in Nagar where the work of the season is the entertainment. Apples, frost, and a table that is always too long for the number of people.",
  },
  {
    id: "desert-kiln",
    name: "Desert Kiln",
    nastaliq: "ریگستان کا بھٹا",
    city: "Bahawalpur",
    region: "Cholistan",
    cover: "/images/stay-desert-kiln.png",
    gallery: ["/images/stay-desert-kiln.png", "/images/stay-indigo-well.png", "/images/dest-gwadar.png"],
    vibes: ["Desert silence", "Family haveli", "Chef’s table"],
    type: "Desert lodge",
    price: 38900,
    storyScore: 93,
    climate: "Best window: Nov–Feb",
    season: "good",
    weather,
    lat: 29.4,
    lng: 71.68,
    pin: { x: 46, y: 62 },
    amenities: ["Kiln terrace", "Night sky", "Camel-distance quiet", "Thal food"],
    rooms: [
      { id: "kiln", name: "Kiln room", sleeps: 2, price: 38900, note: "Terracotta that remembers fire" },
      { id: "dune", name: "Dune suite", sleeps: 2, price: 44500, note: "The sand starts at the step" },
    ],
    stories: [
      { author: "Ibrahim", from: "Cairo", body: "Silence here has a grain. You hear it in your teeth.", mood: "desert silence" },
    ],
    experienceIds: ["cholistan"],
    host: {
      name: "Farid",
      portrait: "/images/host-farid.png",
      years: 7,
      letter: "Cholistan teaches scale. We teach shade, water, and when to stop walking.",
    },
    description:
      "A terracotta lodge at the edge of Cholistan, built around an old kiln. Days are white. Nights are a lecture in stars. Food arrives as if from a slower century.",
  },
  {
    id: "river-lantern",
    name: "River Lantern",
    nastaliq: "دریا کا فانوس",
    city: "Madyan",
    region: "Swat",
    cover: "/images/stay-river-lantern.png",
    gallery: ["/images/stay-river-lantern.png", "/images/stay-pine-key.png", "/images/dest-hunza.png"],
    vibes: ["Lakeside dawn", "Mountain mist", "Chef’s table"],
    type: "River house",
    price: 31200,
    storyScore: 92,
    climate: "Best window: Apr–Jun, Sep–Oct",
    season: "good",
    weather,
    lat: 35.15,
    lng: 72.53,
    pin: { x: 38, y: 22 },
    amenities: ["River balcony", "Lantern supper", "Trout kitchen", "Pine walks"],
    rooms: [
      { id: "lantern", name: "Lantern room", sleeps: 2, price: 31200, note: "The river is the soundtrack" },
      { id: "pine", name: "Pine room", sleeps: 3, price: 33800, note: "Higher, quieter, more needles" },
    ],
    stories: [
      { author: "Fatima", from: "Peshawar", body: "We ate with our feet almost in the water. The lanterns were unnecessary and perfect.", mood: "lakeside dawn" },
    ],
    experienceIds: ["swat-river"],
    host: {
      name: "Saba",
      portrait: "/images/host-saba.png",
      years: 10,
      letter: "Swat is generous if you arrive without a schedule. We keep the lanterns for the hour after the river goes dark.",
    },
    description:
      "Wooden rooms hung over the Swat like a thought. Lanterns, trout, pine. The river does the talking; the house merely agrees.",
  },
  {
    id: "first-light",
    name: "First Light Rooms",
    nastaliq: "پہلی روشنی",
    city: "Islamabad",
    region: "Margalla",
    cover: "/images/stay-first-light.png",
    gallery: ["/images/stay-first-light.png", "/images/stay-pine-key.png", "/images/stay-canal-breeze.png"],
    vibes: ["Work-from-haveli", "Mountain mist", "Quiet courtyard"],
    type: "Hill rooms",
    price: 28900,
    storyScore: 89,
    climate: "Best window: Oct–Apr",
    season: "good",
    weather,
    lat: 33.74,
    lng: 73.08,
    pin: { x: 40, y: 33 },
    amenities: ["Trail at the gate", "Fog windows", "Quiet office hour", "City below, not beside"],
    rooms: [
      { id: "light", name: "First light room", sleeps: 2, price: 28900, note: "Margalla arrives before the inbox" },
      { id: "mist", name: "Mist suite", sleeps: 2, price: 33400, note: "A bath that looks into forest" },
    ],
    stories: [
      { author: "Daniel", from: "Berlin", body: "Islamabad from above is a rumour. The rooms made it a kind one.", mood: "mountain mist" },
    ],
    experienceIds: ["walled"],
    host: {
      name: "Leila",
      portrait: "/images/host-leila.png",
      years: 6,
      letter: "We are twenty minutes from the city and a century from its noise. That is the whole idea.",
    },
    description:
      "Rooms in the Margalla mist for people who need Islamabad without being inside it. First light is not a metaphor here; it is the checkout reminder.",
  },
  {
    id: "truck-art",
    name: "Truck-art Townhouse",
    nastaliq: "فنِ ٹرک",
    city: "Karachi",
    region: "Sindh",
    cover: "/images/stay-truck-art.png",
    gallery: ["/images/stay-truck-art.png", "/images/stay-truckart-townhouse.png", "/images/exp-truckwalk.png", "/images/dest-gwadar.png"],
    vibes: ["Old-city rooftop", "Work-from-haveli", "Family haveli"],
    type: "Townhouse",
    price: 22100,
    storyScore: 87,
    climate: "Best window: Nov–Feb",
    season: "shoulder",
    weather,
    lat: 24.86,
    lng: 67.01,
    pin: { x: 28, y: 82 },
    amenities: ["Painted courtyard", "Roof for sea wind", "Workshop visits", "Late kitchen"],
    rooms: [
      { id: "court", name: "Courtyard room", sleeps: 2, price: 22100, note: "Doors that are a festival" },
      { id: "roof", name: "Roof room", sleeps: 2, price: 25400, note: "Karachi as a working harbour" },
    ],
    stories: [
      { author: "Laila", from: "London", body: "The courtyard was louder than the street and kinder. I did not expect kindness from enamel flowers.", mood: "felt like a film still" },
    ],
    experienceIds: ["truckwalk"],
    host: {
      name: "Farid",
      portrait: "/images/host-farid.png",
      years: 12,
      letter: "Karachi is not for the faint. This house is. Come in, take off the heat, look at the doors until they look back.",
    },
    description:
      "A townhouse whose courtyard doors are painted like the lorries that built this city’s myth. Folk enamel, sea wind, and a roof that understands work.",
  },
];

export const stayById = (id: string) => stays.find((s) => s.id === id);

export const routes = [
  {
    id: "north",
    title: "Apricot then granite",
    nights: "3N Hunza + 2N Skardu",
    stayIds: ["apricot-court", "black-granite"],
    note: "A valley that feeds you, then a river that silences you.",
  },
  {
    id: "south",
    title: "Harbour then wind",
    nights: "2N Karachi + 3N Gwadar",
    stayIds: ["truck-art", "seawind"],
    note: "Paint, salt, and a coast that does not advertise.",
  },
];
